In [1]:
import pandas as pd
import numpy as np

# Criar um DataFrame com valores faltantes
df = pd.DataFrame({'A': [1, 2, np.nan, 4],
                   'B': [5, np.nan, 7, 8],
                   'C': [np.nan, 10, 11, 12],
                   'D': [13, 14, 15, np.nan]})

# Imprimir o DataFrame original
print(df)

# Substituir valores faltantes com a média da coluna
df.fillna(df.mean(), inplace=True)

# Imprimir o DataFrame com os valores faltantes substituídos
print(df)

     A    B     C     D
0  1.0  5.0   NaN  13.0
1  2.0  NaN  10.0  14.0
2  NaN  7.0  11.0  15.0
3  4.0  8.0  12.0   NaN
          A         B     C     D
0  1.000000  5.000000  11.0  13.0
1  2.000000  6.666667  10.0  14.0
2  2.333333  7.000000  11.0  15.0
3  4.000000  8.000000  12.0  14.0


In [4]:
from sklearn.impute import SimpleImputer
import numpy as np
import pandas as pd
# Criar uma matriz com valores faltantes
X = np.array([[1, 2, np.nan],
              [3, np.nan, 4],
              [5, 6, 7]])

# Criar um imputador simples e substituir os valores faltantes pela média
imp = SimpleImputer(strategy='mean')
X_imputed = imp.fit_transform(X)

# Imprimir a matriz original
print(X)

# Imprimir a matriz com os valores faltantes substituídos
print(X_imputed)

[[ 1.  2. nan]
 [ 3. nan  4.]
 [ 5.  6.  7.]]
[[1.  2.  5.5]
 [3.  4.  4. ]
 [5.  6.  7. ]]


In [9]:
pd.DataFrame(X).values

array([[ 1.,  2., nan],
       [ 3., nan,  4.],
       [ 5.,  6.,  7.]])